apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jaeger.yaml
- prometheus.yaml
- grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: model-serving-observability
