apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trainingjob-operator
  namespace: ml-training
  labels:
    app: trainingjob-operator
spec:
  selector:
    matchLabels:
      app: trainingjob-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - ml-training
