apiVersion: v1
kind: Pod
metadata:
  name: debug-gpu-node-priv
  namespace: default
spec:
  containers:
  - name: debugger
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: host-root
      mountPath: /host-root
      readOnly: true
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: host-root
    hostPath:
      path: /
