apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -us-west-2

commonLabels:
  region: us-west-2
  provider: aws

replicas:
- name: ml-serving
  count: 5

patches:
- target:
    kind: Deployment
    name: ml-serving
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "us-west-2"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "aws"

resources:
- hpa.yaml
